[2018-11-08 21:26:05] [    INFO] --- Setup logging. Log file: ./output/gt1/MNIST/output_channels=10/no_cuda=True/08-11-18-21h-26m-05s/logs.txt (setup.py:531)
[2018-11-08 21:26:05] [    INFO] --- Arguments saved to: ./output/gt1/MNIST/output_channels=10/no_cuda=True/08-11-18-21h-26m-05s/args.txt (setup.py:534)
[2018-11-08 21:26:05] [    INFO] --- Initialize Tensorboard SummaryWriter (setup.py:539)
[2018-11-08 21:26:07] [ WARNING] --- Git status is ignored! (RunMe.py:205)
[2018-11-08 21:26:07] [    INFO] --- Randomly chosen seed is: 3924190840 (setup.py:616)
[2018-11-08 21:26:07] [    INFO] --- Model CNN_basic expects input size of (32, 32) (my_task.py:89)
[2018-11-08 21:26:07] [    INFO] --- Loading MNIST from:../SETS/MNIST (setup.py:61)
[2018-11-08 21:26:08] [    INFO] --- Setting up model CNN_basic (setup.py:86)
[2018-11-08 21:26:08] [    INFO] --- Loading weights for data balancing (setup.py:101)
[2018-11-08 21:26:08] [    INFO] --- Loading a saved model (setup.py:117)
[2018-11-08 21:26:08] [   ERROR] --- Unhandled error: FileNotFoundError(2, 'No such file or directory') (RunMe.py:261)
[2018-11-08 21:26:08] [   ERROR] --- Traceback (most recent call last):
  File "./template/RunMe.py", line 254, in _execute
    **args.__dict__)
  File "/home/dusan/DeepDIVA/template/runner/my_task/my_task.py", line 105, in single_run
    with open('samples/synset_words.txt') as lines:
FileNotFoundError: [Errno 2] No such file or directory: 'samples/synset_words.txt'
 (RunMe.py:262)
[2018-11-08 21:26:08] [   ERROR] --- Execution finished with errors :( (RunMe.py:263)
